// Next.js의 Metadata 타입 import
import type { Metadata } from 'next';
// 구글 폰트(GEIST) import
import { Geist, Geist_Mono } from 'next/font/google';
// 공통 스타일 import
import '@/styles/common.scss';

// 테넌트 추출 함수 import
import { getTenantFromHost } from '../lib/tenant';

// Geist Sans 폰트 설정 (CSS 변수로 등록)
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

// Geist Mono 폰트 설정 (CSS 변수로 등록)
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// 메타데이터(SEO 등) 정의
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 루트 레이아웃 컴포넌트
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 서버 헤더에서 host 추출 (실제 배포시 사용, 현재는 주석 처리)
  // const headerList = headers();
  // const host = headerList.get('host');
  // 개발 환경에서는 localhost:3000으로 고정
  const host = 'localhost:3000';
  // host로부터 테넌트 정보 추출
  const tenant = getTenantFromHost(host);
  // 테넌트별 CSS 클래스 생성 (예: tenant-cap, tenant-sk 등)
  const tenantClass = tenant ? `tenant-${tenant}` : undefined;
  return (
    <html lang="ko">
      {/* 폰트 변수와 테넌트 클래스를 body에 적용 */}
      <body className={`${geistSans.variable} ${geistMono.variable} ${tenantClass ?? ''}`}>
        {children}
      </body>
    </html>
  );
}
